# Set Up

In [1]:
!pip install -U sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.1.2)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.57.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.9.0+cu126)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (0.36.0)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (11.3.0)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2.32.4)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.2.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.5.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2025.11.12)

In [2]:
# This cell will authenticate you and mount your Drive in the Colab.
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
from sentence_transformers import SentenceTransformer
import pandas as pd
import torch

In [4]:
# Load a pretrained Sentence Transformer model
model = SentenceTransformer("all-MiniLM-L6-v2")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [5]:
# Read in the datasets made in other code files
perenual_data = pd.read_csv('./drive/MyDrive/DATASCI 266/Project/transformed_wiki_descriptions_with_perenual_data_text.csv')

In [6]:
generated_data = pd.read_csv('./drive/MyDrive/DATASCI 266/Project/transformed_wiki_descriptions_with_generated_descriptions.csv')

In [7]:
class mapping_class:
  def __init__(self, d):
    self._dict = d
  def mapping_func(self, ind):
    return [self._dict[i].lower() for i in ind]

my_map = mapping_class(perenual_data['name'].to_dict())
# my_map.mapping_func(torch.topk(similarities_two, k=10, dim=1).indices.tolist()[0])

# Running Base Model

In [8]:
perenual_data.columns

Index(['user_description', 'name', 'wiki_description', 'perenual_data_text'], dtype='object')

In [9]:
# Calculate embeddings by calling model.encode()
embeddings = model.encode(perenual_data['perenual_data_text'])
print(embeddings.shape)
# [3000, 384]

(1174, 384)

In [10]:
wiki_embeddings = model.encode(perenual_data['user_description'])
print(wiki_embeddings.shape)
# [3000, 384]

(1174, 384)

In [11]:
# Calculate the embedding similarities
similarities = model.similarity(wiki_embeddings, embeddings)
print(similarities)

tensor([[0.5455, 0.4124, 0.5940,  ..., 0.3559, 0.3507, 0.3918],
        [0.4395, 0.5067, 0.3889,  ..., 0.2615, 0.2922, 0.2462],
        [0.4697, 0.4765, 0.5114,  ..., 0.2575, 0.3185, 0.3357],
        ...,
        [0.1890, 0.2943, 0.2405,  ..., 0.3204, 0.4652, 0.3524],
        [0.1934, 0.2575, 0.2877,  ..., 0.4406, 0.5284, 0.4242],
        [0.2312, 0.2951, 0.2740,  ..., 0.4403, 0.4318, 0.4739]])

In [12]:
print(similarities.shape)

torch.Size([1174, 1174])

In [14]:
# Use the similarity to find the predicted plant value
results = pd.DataFrame(perenual_data['name'][torch.argmax(similarities, dim=1).tolist()])
results.rename(columns={'name': 'predicted'}, inplace=True)
results['predicted'] = results['predicted'].str.lower()
results.reset_index(inplace=True, drop=True)
results['actual'] = perenual_data['name'].str.lower()
results['predicted_top_5'] = [i for i in map(my_map.mapping_func, torch.topk(similarities, k=5, dim=1).indices.tolist())]
results['predicted_top_10'] = [i for i in map(my_map.mapping_func, torch.topk(similarities, k=10, dim=1).indices.tolist())]
results

,predicted,actual,predicted_top_5,predicted_top_10
0,fraser fir,european silver fir,"[fraser fir, caucasian fir, alpine fir, mounta...","[fraser fir, caucasian fir, alpine fir, mounta..."
1,grand fir,big leaf maple,"[grand fir, fraser fir, hornbeam maple, tree h...","[grand fir, fraser fir, hornbeam maple, tree h..."
2,fraser fir,alpine fir,"[fraser fir, tree heath, norway spruce, grand ...","[fraser fir, tree heath, norway spruce, grand ..."
3,fraser fir,noble fir,"[fraser fir, mountain mahogany, mountain dogwo...","[fraser fir, mountain mahogany, mountain dogwo..."
4,tree heath,amur maple,"[tree heath, grand fir, silver birch, rain tre...","[tree heath, grand fir, silver birch, rain tre..."
...,...,...,...,...
1169,weeping beech,fokienia,"[weeping beech, norway spruce, grand fir, amer...","[weeping beech, norway spruce, grand fir, amer..."
1170,lanceleaf coreopsis,forsythia,"[lanceleaf coreopsis, spring beauty, candle la...","[lanceleaf coreopsis, spring beauty, candle la..."
1171,joe pye weed,korean forsythia,"[joe pye weed, winter begonia, cardinal larksp...","[joe pye weed, winter begonia, cardinal larksp..."
1172,cardinal larkspur,greenstem forsythia,"[cardinal larkspur, tall bellflower, spring be...","[cardinal larkspur, tall bellflower, spring be..."
1173,spring beauty,weeping forsythia,"[spring beauty, lanceleaf coreopsis, yellow co...","[spring beauty, lanceleaf coreopsis, yellow co..."

In [15]:
# Calculating accuracy
print(f'top 1: {sum(results['predicted'] == results['actual']) / results.shape[0]}')
print(f'top 5: {sum([results['actual'][i] in results['predicted_top_5'][i] for i in range(results.shape[0])]) / results.shape[0]}')
print(f'top 10: {sum([results['actual'][i] in results['predicted_top_10'][i] for i in range(results.shape[0])]) / results.shape[0]}')

top 1: 0.05110732538330494
top 5: 0.13287904599659284
top 10: 0.18824531516183987

# Running Finetuned Model

In [16]:
from datasets import load_dataset
from datasets import Dataset
from sentence_transformers import (
    SentenceTransformer,
    SentenceTransformerTrainer,
    SentenceTransformerTrainingArguments,
    SentenceTransformerModelCardData,
)
from sentence_transformers.losses import CoSENTLoss
from sentence_transformers.training_args import BatchSamplers
from sentence_transformers.evaluation import TripletEvaluator
import os

In [17]:
# Restructure the data for training
joint_df = pd.merge(perenual_data, generated_data, how='outer', right_on = 'name',left_on = 'name')

In [18]:
temp = joint_df['generated_description'].to_list()

In [19]:
temp2 = temp[5:] + temp[:5] # rotate the descriptions around 5 to get some false matches

In [20]:
# temp[0]

In [21]:
# temp2[0]

In [22]:
train_dataset = Dataset.from_dict({
    'sentence1': joint_df['perenual_data_text'].to_list() + joint_df['perenual_data_text'].to_list(),
    'sentence2': joint_df['generated_description'].to_list() + temp2,
    # Scores are typically in a 0 to 1 or 0 to 5 range, normalized to 0-1 for this loss function
    'score': [1] * joint_df.shape[0] + [0] * joint_df.shape[0]
})

In [23]:
# Start with a good pre-trained S-BERT model
model_name = 'all-MiniLM-L6-v2'
model_two = SentenceTransformer(model_name)

In [24]:
os.environ["WANDB_DISABLED"] = "true"

In [25]:
# # look at the layers in the model
# for i in model_two.named_parameters():
#   print(i[0])

In [26]:
# Define a loss function
loss = CoSENTLoss(model_two)

# Specify training args
args = SentenceTransformerTrainingArguments(
    # Required parameter:
    output_dir="models/fine-tuned-sbert",
    # Optional training parameters:
    num_train_epochs=1,
    per_device_train_batch_size=16,
    warmup_ratio=0.1,
    fp16=True,  # Set to False if GPU can't handle FP16
    bf16=False,  # Set to True if GPU supports BF16
    batch_sampler=BatchSamplers.NO_DUPLICATES
)

#freeze all layers except the last layer
for name, param in model_two.named_parameters():
    if not 'layer.5' in name:
        param.requires_grad = False

# Train
trainer = SentenceTransformerTrainer(
    model=model_two,
    args=args,
    train_dataset=train_dataset,
    loss=loss
)
trainer.train()

# Save the trained model
model_two.save_pretrained("models/fine-tuned-sbert/final")

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

Computing widget examples:   0%|          | 0/1 [00:00<?, ?example/s]

In [27]:
# Calculate embeddings by calling model.encode()
embeddings_two = model_two.encode(perenual_data['perenual_data_text'])
print(embeddings_two.shape)
# [3000, 384]

(1174, 384)

In [28]:
wiki_embeddings_two = model_two.encode(perenual_data['user_description'])

In [29]:
# Calculate the embedding similarities
similarities_two = model_two.similarity(wiki_embeddings_two, embeddings_two)
print(similarities)

tensor([[0.5455, 0.4124, 0.5940,  ..., 0.3559, 0.3507, 0.3918],
        [0.4395, 0.5067, 0.3889,  ..., 0.2615, 0.2922, 0.2462],
        [0.4697, 0.4765, 0.5114,  ..., 0.2575, 0.3185, 0.3357],
        ...,
        [0.1890, 0.2943, 0.2405,  ..., 0.3204, 0.4652, 0.3524],
        [0.1934, 0.2575, 0.2877,  ..., 0.4406, 0.5284, 0.4242],
        [0.2312, 0.2951, 0.2740,  ..., 0.4403, 0.4318, 0.4739]])

In [30]:
# Use the similarity to find the predicted plant value
results_two = pd.DataFrame(perenual_data['name'][torch.argmax(similarities_two, dim=1).tolist()])
results_two.rename(columns={'name': 'predicted'}, inplace=True)
results_two['predicted'] = results_two['predicted'].str.lower()
results_two.reset_index(inplace=True, drop=True)
results_two['actual'] = perenual_data['name'].str.lower()
results_two['predicted_top_5'] = [i for i in map(my_map.mapping_func, torch.topk(similarities_two, k=5, dim=1).indices.tolist())]
results_two['predicted_top_10'] = [i for i in map(my_map.mapping_func, torch.topk(similarities_two, k=10, dim=1).indices.tolist())]
results_two

,predicted,actual,predicted_top_5,predicted_top_10
0,fraser fir,european silver fir,"[fraser fir, caucasian fir, alpine fir, mounta...","[fraser fir, caucasian fir, alpine fir, mounta..."
1,grand fir,big leaf maple,"[grand fir, tree heath, hornbeam maple, fraser...","[grand fir, tree heath, hornbeam maple, fraser..."
2,fraser fir,alpine fir,"[fraser fir, tree heath, grand fir, norway spr...","[fraser fir, tree heath, grand fir, norway spr..."
3,mountain palm,noble fir,"[mountain palm, mountain mahogany, alps yarrow...","[mountain palm, mountain mahogany, alps yarrow..."
4,tree heath,amur maple,"[tree heath, grand fir, chehalis apple, hornbe...","[tree heath, grand fir, chehalis apple, hornbe..."
...,...,...,...,...
1169,norway spruce,fokienia,"[norway spruce, weeping beech, grand fir, amur...","[norway spruce, weeping beech, grand fir, amur..."
1170,lanceleaf coreopsis,forsythia,"[lanceleaf coreopsis, spring beauty, dahlia, y...","[lanceleaf coreopsis, spring beauty, dahlia, y..."
1171,joe pye weed,korean forsythia,"[joe pye weed, winter begonia, blue ginger, ph...","[joe pye weed, winter begonia, blue ginger, ph..."
1172,cardinal larkspur,greenstem forsythia,"[cardinal larkspur, tall bellflower, decorativ...","[cardinal larkspur, tall bellflower, decorativ..."
1173,yellow coneflower,weeping forsythia,"[yellow coneflower, lanceleaf coreopsis, dahli...","[yellow coneflower, lanceleaf coreopsis, dahli..."

In [31]:
# Calculating accuracy
print(f'top 1: {sum(results_two['predicted'] == results_two['actual']) / results_two.shape[0]}')
print(f'top 5: {sum([results_two['actual'][i] in results_two['predicted_top_5'][i] for i in range(results_two.shape[0])]) / results_two.shape[0]}')
print(f'top 10: {sum([results_two['actual'][i] in results_two['predicted_top_10'][i] for i in range(results_two.shape[0])]) / results_two.shape[0]}')

top 1: 0.05025553662691652
top 5: 0.141396933560477
top 10: 0.2018739352640545

# Looking into missed values

In [32]:
# Looking into the ones that were off
results_two[results_two['predicted'] != results_two['actual']]

,predicted,actual,predicted_top_5,predicted_top_10
0,fraser fir,european silver fir,"[fraser fir, caucasian fir, alpine fir, mounta...","[fraser fir, caucasian fir, alpine fir, mounta..."
1,grand fir,big leaf maple,"[grand fir, tree heath, hornbeam maple, fraser...","[grand fir, tree heath, hornbeam maple, fraser..."
2,fraser fir,alpine fir,"[fraser fir, tree heath, grand fir, norway spr...","[fraser fir, tree heath, grand fir, norway spr..."
3,mountain palm,noble fir,"[mountain palm, mountain mahogany, alps yarrow...","[mountain palm, mountain mahogany, alps yarrow..."
4,tree heath,amur maple,"[tree heath, grand fir, chehalis apple, hornbe...","[tree heath, grand fir, chehalis apple, hornbe..."
...,...,...,...,...
1169,norway spruce,fokienia,"[norway spruce, weeping beech, grand fir, amur...","[norway spruce, weeping beech, grand fir, amur..."
1170,lanceleaf coreopsis,forsythia,"[lanceleaf coreopsis, spring beauty, dahlia, y...","[lanceleaf coreopsis, spring beauty, dahlia, y..."
1171,joe pye weed,korean forsythia,"[joe pye weed, winter begonia, blue ginger, ph...","[joe pye weed, winter begonia, blue ginger, ph..."
1172,cardinal larkspur,greenstem forsythia,"[cardinal larkspur, tall bellflower, decorativ...","[cardinal larkspur, tall bellflower, decorativ..."
1173,yellow coneflower,weeping forsythia,"[yellow coneflower, lanceleaf coreopsis, dahli...","[yellow coneflower, lanceleaf coreopsis, dahli..."

In [33]:
perenual_data[perenual_data['name'].str.lower()=='palmatifidum japanese maple*']

Empty DataFrame
Columns: [user_description, name, wiki_description, perenual_data_text]
Index: []

In [34]:
results_two[[not (results_two['actual'][i] in results_two['predicted_top_10'][i]) for i in range(results_two.shape[0])]]

,predicted,actual,predicted_top_5,predicted_top_10
1,grand fir,big leaf maple,"[grand fir, tree heath, hornbeam maple, fraser...","[grand fir, tree heath, hornbeam maple, fraser..."
2,fraser fir,alpine fir,"[fraser fir, tree heath, grand fir, norway spr...","[fraser fir, tree heath, grand fir, norway spr..."
3,mountain palm,noble fir,"[mountain palm, mountain mahogany, alps yarrow...","[mountain palm, mountain mahogany, alps yarrow..."
4,tree heath,amur maple,"[tree heath, grand fir, chehalis apple, hornbe...","[tree heath, grand fir, chehalis apple, hornbe..."
5,sugar maple,fullmoon maple,"[sugar maple, japanese maple, big leaf maple, ...","[sugar maple, japanese maple, big leaf maple, ..."
...,...,...,...,...
1169,norway spruce,fokienia,"[norway spruce, weeping beech, grand fir, amur...","[norway spruce, weeping beech, grand fir, amur..."
1170,lanceleaf coreopsis,forsythia,"[lanceleaf coreopsis, spring beauty, dahlia, y...","[lanceleaf coreopsis, spring beauty, dahlia, y..."
1171,joe pye weed,korean forsythia,"[joe pye weed, winter begonia, blue ginger, ph...","[joe pye weed, winter begonia, blue ginger, ph..."
1172,cardinal larkspur,greenstem forsythia,"[cardinal larkspur, tall bellflower, decorativ...","[cardinal larkspur, tall bellflower, decorativ..."
1173,yellow coneflower,weeping forsythia,"[yellow coneflower, lanceleaf coreopsis, dahli...","[yellow coneflower, lanceleaf coreopsis, dahli..."

In [35]:
results_two['predicted_top_10'][4]

['tree heath',
 'grand fir',
 'chehalis apple',
 'hornbeam maple',
 'silver birch',
 'mountain bush honeysuckle',
 'sourwood',
 'small-leaved cotoneaster',
 'rain tree',
 'hazel alder']